# Generated by Django 6.0.4 on 2026-05-04 05:31

import app_base.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, verbose_name='Product ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField(default=0.0, validators=[app_base.models.price_validate])),
                ('quantity', models.FloatField(default=0, validators=[app_base.models.quantity_validate])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products', validators=[app_base.models.validate_file_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), app_base.models.validate_image_type, app_base.models.validate_image_resulation])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_base.productinfo')),
            ],
        ),
    ]
